databases:
  - name: album-review
    databaseName: album_review
    user: album_review_user

services:
  - type: web
    name: abum-rebiew-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: album_review
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false